import { createContext, useContext, useState } from 'react';

const LANG_KEY = 'portal-lang';

const EN = {
  tagline: 'Get online instantly via M-Pesa',
  taglineSub: 'Secure access via M-Pesa',
  loading: 'Preparing your packages...',
  footerManaged: 'Managed by',
  trialTitle: (m) => `🎁 Try free for ${m} minutes`,
  trialCopy: 'New here? Experience the speed before you pay — no M-Pesa needed.',
  trialStart: (m) => `Start ${m}-minute free trial`,
  trialStarting: 'Starting…',
  welcomeBack: 'Welcome back!',
  activeSession: 'You already have an active session. Logging you in…',
  topUp: 'Top Up / Buy Another Bundle',
  alreadyHaveCode: 'already have a code?',
  enterVoucher: '🎟 Enter voucher or M-Pesa receipt',
  choosePackage: 'Choose a package',
  selectPlan: 'Select the access plan that fits your session',
  quickCheckout: 'Fast checkout, instant activation, and easy re-entry if your device reconnects.',
  timePlans: '⏱ Time Plans',
  dataPlans: '📊 Data Plans',
  noTimePlans: 'No time plans available right now',
  noDataPlans: 'No data plans available right now',
  switchTabs: 'Switch tabs or refresh once packages are published for this operator.',
  continueWith: (name) => `Continue with ${name}`,
  continueArrow: 'Continue →',
  quickHeadsUp: 'Quick heads-up',
  mpesaInfo: 'The M-Pesa prompt will be sent to the number you enter below. Confirm with your PIN and stay on this page while we activate access.',
  mpesaNumber: 'M-Pesa number',
  phonePlaceholder: '712 345 678',
  phoneHint: 'Use the number that should receive the STK push prompt.',
  payBtn: (price) => `Pay KES ${price} via M-Pesa`,
  sendingPrompt: 'Sending prompt…',
  backToPlans: '← Back to plans',
  invalidPhone: 'Enter a valid Kenyan number e.g. 0712 345 678',
  manualAccess: 'Manual access',
  redeemTitle: 'Redeem a voucher or receipt',
  redeemCopy1: 'Perfect if you already paid earlier or received an access code from the operator.',
  enterCode: 'Enter your code',
  codePlaceholder: 'WIFI-XXXX-XXXX or M-Pesa receipt',
  codeHint: 'Codes are not case-sensitive. We automatically clean and verify them.',
  connectNow: 'Connect now',
  checkingCode: 'Checking code…',
  codeAccepted: 'Code accepted!',
  connectingNow: 'Connecting you now…',
  sessionActive: 'Your session is still active. Logging you in…',
  checkYourPhone: 'Check your phone',
  stkSent: 'An M-Pesa STK push has been sent to your number. Enter your PIN to confirm payment.',
  networkLost: 'Network connection lost — waiting to reconnect.',
  dontClose: "Your payment is still being tracked. Don't close this page.",
  howToComplete: 'How to complete:',
  popupHint: 'A pop-up will appear on your phone asking for your M-Pesa PIN. Enter it to pay and get connected instantly.',
  keepOpen: 'Keep this page open while we confirm payment and activate access.',
  connected: "You're connected!",
  paymentConfirmed: 'Payment confirmed. Logging you in automatically…',
  accessUntil: 'Access until',
  paymentFailed: 'Payment failed',
  notCompleted: 'Your M-Pesa transaction was not completed. You were not charged.',
  tryAgain: 'Try again',
  paymentCancelled: 'Payment cancelled',
  youCancelled: 'You cancelled the M-Pesa prompt.',
  paymentReceived: 'Payment received',
  activating: 'We got your payment, but activating internet access is taking longer than expected.',
  retryActivation: 'Retry activation',
  retryingActivation: 'Retrying activation…',
  ifStuck: 'If it still does not connect, contact support:',
  takingLong: 'Taking longer than expected',
  couldNotConfirm: "We couldn't confirm your payment automatically.",
  verifyPayment: 'Verify my payment',
  checkingMpesa: 'Checking M-Pesa…',
  startOver: 'Start over',
  charged: 'Were you charged but not connected?',
  verifyAbove: 'Press "Verify my payment" above — it checks M-Pesa directly and activates your session if the payment went through.',
  stillStuck: 'Still stuck? Contact support:',
};

const SW = {
  tagline: 'Ingia mtandaoni mara moja kupitia M-Pesa',
  taglineSub: 'Ufikiaji salama kupitia M-Pesa',
  loading: 'Inatayarisha vifurushi vyako...',
  footerManaged: 'Inayosimamiwa na',
  trialTitle: (m) => `🎁 Jaribu bure kwa dakika ${m}`,
  trialCopy: 'Mara ya kwanza? Jaribu kasi kabla ya kulipa — bila M-Pesa.',
  trialStart: (m) => `Anza jaribio la dakika ${m} bila malipo`,
  trialStarting: 'Inaanza…',
  welcomeBack: 'Karibu tena!',
  activeSession: 'Una kipindi kinachoendelea. Unaingiwa ndani…',
  topUp: 'Weka Zaidi / Nunua Kifurushi Kingine',
  alreadyHaveCode: 'una nambari tayari?',
  enterVoucher: '🎟 Weka vocha au stakabadhi ya M-Pesa',
  choosePackage: 'Chagua kifurushi',
  selectPlan: 'Chagua mpango unaofaa kikao chako',
  quickCheckout: 'Malipo ya haraka, uanzishwaji wa papo hapo, na uingiaji rahisi ukiunganishwa tena.',
  timePlans: '⏱ Mipango ya Muda',
  dataPlans: '📊 Mipango ya Data',
  noTimePlans: 'Hakuna mipango ya muda kwa sasa',
  noDataPlans: 'Hakuna mipango ya data kwa sasa',
  switchTabs: 'Badilisha kichupo au onyesha upya mara vifurushi vitakapochapishwa.',
  continueWith: (name) => `Endelea na ${name}`,
  continueArrow: 'Endelea →',
  quickHeadsUp: 'Taarifa fupi',
  mpesaInfo: 'Ombi la M-Pesa litatumwa kwa nambari unayoingiza hapa chini. Thibitisha kwa PIN yako na kaa ukurasa huu tunapowezesha ufikiaji.',
  mpesaNumber: 'Nambari ya M-Pesa',
  phonePlaceholder: '712 345 678',
  phoneHint: 'Tumia nambari itakayopokea ombi la STK push.',
  payBtn: (price) => `Lipa KES ${price} kupitia M-Pesa`,
  sendingPrompt: 'Inatuma ombi…',
  backToPlans: '← Rudi kwenye mipango',
  invalidPhone: 'Weka nambari sahihi ya Kenya, mfano 0712 345 678',
  manualAccess: 'Ufikiaji wa mwenyewe',
  redeemTitle: 'Tumia vocha au stakabadhi',
  redeemCopy1: 'Bora ikiwa umelipa awali au umepokea nambari ya ufikiaji kutoka kwa opereta.',
  enterCode: 'Weka nambari yako',
  codePlaceholder: 'WIFI-XXXX-XXXX au stakabadhi ya M-Pesa',
  codeHint: 'Nambari hazijali herufi ndogo au kubwa. Tunazisafisha na kuzithibitisha kiotomatiki.',
  connectNow: 'Unganika sasa',
  checkingCode: 'Inakagua nambari…',
  codeAccepted: 'Nambari imekubaliwa!',
  connectingNow: 'Inakuunganisha sasa…',
  sessionActive: 'Kikao chako bado kipo. Unaingiwa ndani…',
  checkYourPhone: 'Angalia simu yako',
  stkSent: 'Ombi la M-Pesa STK limetumwa kwa nambari yako. Weka PIN yako kuthibitisha malipo.',
  networkLost: 'Muunganiko wa mtandao umepotea — inasubiri.',
  dontClose: 'Malipo yako bado yanafuatiliwa. Usifunge ukurasa huu.',
  howToComplete: 'Jinsi ya kukamilisha:',
  popupHint: 'Ujumbe utaonekana kwenye simu yako ukiomba PIN yako ya M-Pesa. Weka PIN kulipa na kuunganishwa mara moja.',
  keepOpen: 'Baki ukurasa huu tunapothibitisha malipo na kuwezesha ufikiaji.',
  connected: 'Umeunganishwa!',
  paymentConfirmed: 'Malipo yamethibitishwa. Unaingiwa ndani kiotomatiki…',
  accessUntil: 'Ufikiaji hadi',
  paymentFailed: 'Malipo hayakufanikiwa',
  notCompleted: 'Muamala wako wa M-Pesa haukukamilika. Haukutozwa malipo.',
  tryAgain: 'Jaribu tena',
  paymentCancelled: 'Malipo yamefutwa',
  youCancelled: 'Ulighairi ombi la M-Pesa.',
  paymentReceived: 'Malipo yamepokelewa',
  activating: 'Tulipokea malipo yako, lakini kuwezesha ufikiaji wa intaneti kunachukua muda zaidi.',
  retryActivation: 'Jaribu kuwezesha tena',
  retryingActivation: 'Inajaribu kuwezesha tena…',
  ifStuck: 'Ikiwa haijaunganika bado, wasiliana na msaada:',
  takingLong: 'Inachukua muda zaidi kuliko ilivyotarajiwa',
  couldNotConfirm: 'Hatukuweza kuthibitisha malipo yako kiotomatiki.',
  verifyPayment: 'Thibitisha malipo yangu',
  checkingMpesa: 'Inakagua M-Pesa…',
  startOver: 'Anza upya',
  charged: 'Je, ulitozwa lakini hukuunganishwa?',
  verifyAbove: 'Bonyeza "Thibitisha malipo yangu" hapo juu — inakagua M-Pesa moja kwa moja na kuwezesha kikao chako ikiwa malipo yalipita.',
  stillStuck: 'Bado ukiwa na tatizo? Wasiliana na msaada:',
};

const LangContext = createContext({ lang: 'en', t: EN, toggle: () => {} });

export const useLang = () => useContext(LangContext);

export function LangProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem(LANG_KEY) || 'en');

  const toggle = () => {
    const next = lang === 'en' ? 'sw' : 'en';
    localStorage.setItem(LANG_KEY, next);
    setLang(next);
  };

  const t = lang === 'sw' ? SW : EN;
  return (
    <LangContext.Provider value={{ lang, t, toggle }}>
      {children}
    </LangContext.Provider>
  );
}
