const mongoose = require('mongoose');

const RedemptionSchema = new mongoose.Schema({
  macAddress: { type: String, default: '' },
  phone: { type: String, default: '' },
  sessionId: { type: mongoose.Schema.Types.ObjectId, ref: 'Session' },
  redeemedAt: { type: Date, default: Date.now },
}, { _id: false });

const VoucherSchema = new mongoose.Schema({
  code: {
    type: String,
    required: true,
    unique: true,
    uppercase: true,
    trim: true,
    index: true,
  },
  // MPESA = auto-created from receipt; ADMIN = batch-generated by admin; PROMO = free/promotional
  type: {
    type: String,
    enum: ['MPESA', 'ADMIN', 'PROMO'],
    required: true,
  },
  bundleId: { type: mongoose.Schema.Types.ObjectId, ref: 'Bundle', required: true },
  operatorId: { type: mongoose.Schema.Types.ObjectId, ref: 'Operator', default: null },
  status: {
    type: String,
    enum: ['ACTIVE', 'FULLY_REDEEMED', 'EXPIRED', 'REVOKED'],
    default: 'ACTIVE',
  },
  // How many devices can redeem this code in total (ever)
  maxDevices: { type: Number, default: 1, min: 1 },
  redemptions: [RedemptionSchema],
  // Admin who generated this (null for MPESA auto-vouchers)
  createdBy: { type: mongoose.Schema.Types.ObjectId, ref: 'AdminUser', default: null },
  // Source transaction (for MPESA type)
  transactionId: { type: mongoose.Schema.Types.ObjectId, ref: 'Transaction', default: null },
  // Code must be redeemed before this date (null = never expires)
  expiresAt: { type: Date, default: null },
  // Groups batch-generated codes together
  batchId: { type: String, default: null },
  note: { type: String, default: '' },
}, { timestamps: true });

module.exports = mongoose.model('Voucher', VoucherSchema);
